FROM node:20-alpine AS build
WORKDIR /app
RUN apk add --no-cache bash git
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
FROM node:20-alpine AS prod
WORKDIR /app
COPY --from=build /app/.output ./
EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]
